// Package handlers has the http handler for all resources
// all the handlers here are autogenerated using the details from contracts
package handlers

//go:generate goscinny handler -path ../../../pkg/contracts/
