// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by generator router -p ../../pkg/contracts/ DO NOT EDIT
package main

import (
	"net/http"

	"github.com/govindarajan/anomalydetection/anomix/cmd/http/handlers"
	"github.com/labstack/echo"
)

// AddRoutes attaches the routes
//go:generate goscinny router -p ../../pkg/contracts/
func AddRoutes(e *echo.Echo) {
	e.Any("/metrics/:metricName", handlers.MetricsHandler{}.Any)
	e.Any("/metrics/:metricName/datapoint", handlers.DataPointHandler{}.Any)
	e.GET("/", func(ctx echo.Context) error {
		return ctx.JSON(http.StatusOK, Heartbeat())
	})
}
