// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by rest_tool -t BasicAuthCredentials -m  validator
package contracts

// Validate checks if a contract is valid or not and return with appropriate message
func (_receiver_ *BasicAuthCredentials) Validate() *Error {
	if _receiver_.UserName == nil {
		return ErrBadRequestParametersMissing("UserName  is mandatory")
	}
	if _receiver_.Password == nil {
		return ErrBadRequestParametersMissing("Password  is mandatory")
	}
	return nil
}
