// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by rest_tool -t BearerAuthCredentials -m  validator
package contracts

// Validate checks if a contract is valid or not and return with appropriate message
func (_receiver_ *BearerAuthCredentials) Validate() *Error {
	if _receiver_.Token == nil {
		return ErrBadRequestParametersMissing("Token  is mandatory")
	}
	return nil
}
