// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by rest_tool -t CreateDataPointRequest -m  validator
package contracts

// Validate checks if a contract is valid or not and return with appropriate message
func (_receiver_ *CreateDataPointRequest) Validate() *Error {
	if _receiver_.Name == nil {
		return ErrBadRequestParametersMissing("Name  is mandatory")
	}
	if _receiver_.Time == nil {
		return ErrBadRequestParametersMissing("Time  is mandatory")
	}
	if _receiver_.Value == nil {
		return ErrBadRequestParametersMissing("Value  is mandatory")
	}
	if _receiver_.Request != nil {
		if typ, ok := interface{}(_receiver_.Request).(Validator); ok {
			if err := typ.Validate(); err != nil {
				return err
			}
		}
	}
	if _receiver_.Time != nil {
		if _time_, ok := interface{}(_receiver_.Time).(Validator); ok {
			if err := _time_.Validate(); err != nil {
				return err
			}
		}
	}
	return nil
}
