// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by goscinny extractor -t CreateDataPointRequest DO NOT EDIT
package contracts

import (
	"time"

	"github.com/labstack/echo"
)

// ExtractFromHTTP reads http request body and fills the object
func (_receiver *CreateDataPointRequest) ExtractFromHTTP(c echo.Context) *Error {
	request := c.Request()
	contentType := request.Header.Get("content-type")
	if request.ContentLength > 0 {
		if err := ContentDecoder(contentType)(request.Body).Decode(_receiver); err != nil {
			if _, ok := err.(Error); ok {
				return ErrBadRequestInvalidParameter("request format is invalid")
			}
			return ErrBadRequestInvalidBody(err.Error())
		}
	}
	if _receiver.Name == nil {
		Name := c.Param("metricName")
		if Name != "" {
			_receiver.Name = &Name
		}
	}
	_request__tmp := new(Request)
	if _request_, ok := interface{}(_receiver.Request).(Extractor); ok {
		_receiver.Request = new(Request)
		if err := _request_.ExtractFromHTTP(c); err != nil {
			return err
		}
		if *_receiver.Request == *_request__tmp {
			_receiver.Request = nil
		}
	}
	_time__tmp := new(time.Time)
	if _time_, ok := interface{}(_receiver.Time).(Extractor); ok {
		_receiver.Time = new(time.Time)
		if err := _time_.ExtractFromHTTP(c); err != nil {
			return err
		}
		if *_receiver.Time == *_time__tmp {
			_receiver.Time = nil
		}
	}
	return nil
}
