// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by rest_tool -t Request -m  validator
package contracts

// Validate checks if a contract is valid or not and return with appropriate message
func (_receiver_ *Request) Validate() *Error {
	if _receiver_.Method == nil {
		return ErrBadRequestParametersMissing("Method  is mandatory")
	}
	if _receiver_.RequestID == nil {
		return ErrBadRequestParametersMissing("RequestID  is mandatory")
	}
	return nil
}
