// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// Autogenerated by rest_tool -t SingleResponse -m  validator
package contracts

// Validate checks if a contract is valid or not and return with appropriate message
func (_receiver_ *SingleResponse) Validate() *Error {
	if _receiver_.Status != nil {
		switch *_receiver_.Status {
		case "failure|success":
		default:
			return ErrBadRequestInvalidParameter("valid values for Status are failure|success")
		}
	}
	if _receiver_.ErrorData != nil {
		if _errordata_, ok := interface{}(_receiver_.ErrorData).(Validator); ok {
			if err := _errordata_.Validate(); err != nil {
				return err
			}
		}
	}
	return nil
}
